### PR TITLE
Fix: Add i18n object in `onRequest`

### PR DESCRIPTION
**Pull request by rluba**
… to ensure that it’s available in `onPreResponse` in case no route was found.

### CODE REVIEW

**Comment by kaywolter** [comment]
Hi and thanks for your contribution. You commit message states that you added i18n in "onRequest" extension point but the diff shows another "onPreAuth" request extension. Is this intended? Can you please add a test case that covers your fix?

**Comment by rluba** [comment]
Hi @kaywolter,

thank you. That was a real blunder of mine. We’ve had this fix in production for years and I made a mistake when porting it to the current `master` of hapi-i18n.

I’ll add a test as well to demonstrate the issue.

**Comment by kaywolter** [comment]
Thanks a lot, looks good now :)

**Comment by kaywolter** [comment]
I released new version 2.1.2 with your fix.

**Pull request merged**
